from pathlib import Path
from typing import Optional

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    neo4j_uri: str
    neo4j_user: str
    neo4j_password: str
    neo4j_db: str

    # LLM Provider
    llm_provider: str = "groq"

    # Groq
    groq_api_key: Optional[str] = None
    groq_model: Optional[str] = None

    # Schema file for NL→Cypher (generated by scripts/generate_schema.py). Relative to phase2/code or absolute.
    schema_file: str = "nl2cypher/prompt_schema/graph_schema.txt"

    class Config:
        env_file = ".env"
        extra = "ignore"


settings = Settings()


def get_schema_path() -> Path:
    """Resolve schema file path: relative to phase2/code (this package root) or absolute."""
    p = Path(settings.schema_file)
    if p.is_absolute():
        return p
    # Assume running from phase2/code; config.py lives in core/
    code_root = Path(__file__).resolve().parent.parent
    return code_root / settings.schema_file
